// This file is auto-generated by the jankiest code evr!
#include "json_archive.h"
#include "${generated_include}"

% for ns in params['namespaces']:
namespace ${ns['name']} 
{
% for Class in ns['classes']:
    void ArchiveJson(${Class['full_name']}& target, Archive& archive )
    {
% for m in Class['members']:
        ArchiveByPointer( target.${m['name']}, "/${m['name']}", archive );
% endfor
    }
% endfor
}
% endfor
