// This file is auto-generated by the jankiest code evr!
#pragma once
#include "${params['include']}"

namespace Saleae
{
    struct Archive;
}

% for ns in params['namespaces']:
namespace ${ns['name']} 
{
% for Class in ns['classes']:
    void ArchiveJson(${Class['full_name']}& target, Archive& archive );
% endfor
}
% endfor
