// This file is auto-generated by the jankiest code evr!
import { AnalogValue, Map } from "./ts_helpers";

% for ns in params['namespaces']:
% for Class in ns['classes']:
export interface ${Class['name']} {
% for m in Class['members']:
  ${m['json_name']}: ${m['ts_type']};
% endfor
}
% endfor
% endfor
