// This file is auto-generated by the jankiest code evr!
import { AnalogValue, Map } from "./ts_helpers";

export interface RenderRequestData {
  id: number;
  widthPx: number;
  leftEdgeTime: number;
  secondsPerPx: number;
  startGraphTime: GraphTime;
}
export interface Vec2 {
  x: number;
  y: number;
}
export interface Line {
  from: Vec2;
  to: Vec2;
}
export interface RenderResponseData {
  id: number;
  valueSet: ValueSet;
  lines: Line[];
  lineStrip: Vec2[];
}
export interface ValueSet {
  values: AnalogValue[];
  firstSampleTime: number;
  sampleRate: number;
}
