// This file is auto-generated by the jankiest code evr!
#pragma once
#include "converter.h"
#include "render_data.h"

namespace Saleae
{
    struct Archive;
}

namespace Saleae::Graph 
{
    void ArchiveJson(RenderRequestData& target, Archive& archive );
    void ArchiveJson(Vec2& target, Archive& archive );
    void ArchiveJson(Line& target, Archive& archive );
    void ArchiveJson(RenderResponseData& target, Archive& archive );
    void ArchiveJson(RenderResponseData::ValueSet& target, Archive& archive );

    using RenderRequestDataArchiveJsonConverter = ArchiveJsonConverter<RenderRequestData>;
    using RenderResponseDataArchiveJsonConverter = ArchiveJsonConverter<RenderResponseData>;
}
