// This file is auto-generated by the jankiest code evr!
#include "json_archive.h"
#include "render_data.gen2.h"

namespace Saleae::Graph 
{
    void ArchiveJson(RenderRequestData& target, Archive& archive )
    {
        ArchiveByPointer( target.mId, "/mId", archive );
        ArchiveByPointer( target.mWidthPx, "/mWidthPx", archive );
        ArchiveByPointer( target.mLeftEdgeTime, "/mLeftEdgeTime", archive );
        ArchiveByPointer( target.mSecondsPerPx, "/mSecondsPerPx", archive );
        ArchiveByPointer( target.mStartGraphTime, "/mStartGraphTime", archive );
    }
    void ArchiveJson(Vec2& target, Archive& archive )
    {
        ArchiveByPointer( target.mX, "/mX", archive );
        ArchiveByPointer( target.mY, "/mY", archive );
    }
    void ArchiveJson(Line& target, Archive& archive )
    {
        ArchiveByPointer( target.mFrom, "/mFrom", archive );
        ArchiveByPointer( target.mTo, "/mTo", archive );
    }
    void ArchiveJson(RenderResponseData& target, Archive& archive )
    {
        ArchiveByPointer( target.mId, "/mId", archive );
        ArchiveByPointer( target.mValueSet, "/mValueSet", archive );
        ArchiveByPointer( target.mLines, "/mLines", archive );
        ArchiveByPointer( target.mLineStrip, "/mLineStrip", archive );
    }
    void ArchiveJson(RenderResponseData::ValueSet& target, Archive& archive )
    {
        ArchiveByPointer( target.mValues, "/mValues", archive );
        ArchiveByPointer( target.mFirstSampleTime, "/mFirstSampleTime", archive );
        ArchiveByPointer( target.mSampleRate, "/mSampleRate", archive );
    }
}
