// This file is auto-generated by the jankiest code evr!

export interface RenderRequestData {
    id: number;
    widthPx: number;
    leftEdgeTime: number;
    secondsPerPx: number;
}
export interface Vec2 {
    x: number;
    y: number;
}
export interface Line {
    from: Vec2;
    to: Vec2;
}
export interface RenderResponseData {
    id: number;
    valueSet: ValueSet;
    lines: number;
    lineStrip: number;
}
export interface ValueSet {
    values: number;
    firstSampleTime: number;
    sampleRate: number;
}
