// This file is auto-generated by the jankiest code evr!
#pragma once
#include <string>
#include <cereal/archives/json.hpp>
#include "server.h"

namespace Api 
{
    std::string ParseMessageForGraphServer( GraphServer& target, std::string message );
}
